CREATE TABLE ARTICLE
(
	ArticleID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Title VARCHAR(500),
	Content VARCHAR(40000),
	DateModified TIMESTAMP,
	ImgURLs VARCHAR(5000),
	ArticleURL VARCHAR(500),
	Author VARCHAR(100)
);

CREATE TABLE TEAM
(
	TeamID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TeamName VARCHAR(100)
);