CREATE TABLE ARTICLE
(
	ArticleID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Title VARCHAR(500),
	Header VARCHAR(5000),
	Content VARCHAR(40000),
	DateModified TIMESTAMP,
	ImgURLs VARCHAR(5000),
	ArticleURL VARCHAR(500),
	SourceID INT NOT NULL,
	FOREIGN KEY (SourceID) REFERENCES SOURCE (SourceID)
);

CREATE TABLE COUNTRY
(
	CountryID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CountryName VARCHAR(100) 
);

CREATE TABLE TEAM
(
	TeamID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TeamName VARCHAR(100),
	CountryID INT NOT NULL,
	FOREIGN KEY (CountryID) REFERENCES COUNTRY (CountryID)
);

CREATE TABLE TEAMNEWS
(
	ArticleID INT NOT NULL,
	TeamID INT NOT NULL,
	FOREIGN KEY (ArticleID) REFERENCES ARTICLE (ArticleID),
	FOREIGN KEY (TeamID) REFERENCES TEAM (TeamID),
	PRIMARY KEY (ArticleID, TeamID)
);

CREATE TABLE SOURCE
(
	SourceID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	SourceName VARCHAR(50) NOT NULL
);