/*Inserting countries*/
INSERT INTO COUNTRY VALUES (1,'ENGLAND');
INSERT INTO COUNTRY VALUES (2,'ITALY');
INSERT INTO COUNTRY VALUES (3,'SPAIN');
INSERT INTO COUNTRY VALUES (4,'FRANCE');
INSERT INTO COUNTRY VALUES (5,'GERMANY');

/*Inserting teams*/
INSERT INTO TEAM VALUES(1,'ARSENAL',1);
INSERT INTO TEAM VALUES(2,'ASTON VILLA',1);
INSERT INTO TEAM VALUES(3,'CHELSEA',1);
INSERT INTO TEAM VALUES(4,'EVERTON',1);
INSERT INTO TEAM VALUES(5,'FULHAM',1);
INSERT INTO TEAM VALUES(6,'LIVERPOOL',1);
INSERT INTO TEAM VALUES(7,'MANCHESTER CITY',1);
INSERT INTO TEAM VALUES(8,'MANCHESTER UNITED',1);
INSERT INTO TEAM VALUES(9,'NEWCASTLE',1);
INSERT INTO TEAM VALUES(10,'NORWICH',1);
INSERT INTO TEAM VALUES(11,'QPR',1);
INSERT INTO TEAM VALUES(12,'READING',1);
INSERT INTO TEAM VALUES(13,'SOUTHAMPTON',1);
INSERT INTO TEAM VALUES(14,'STOKE',1);
INSERT INTO TEAM VALUES(15,'SUNDERLAND',1);
INSERT INTO TEAM VALUES(16,'SWANSEA',1);
INSERT INTO TEAM VALUES(17,'TOTTENHAM',1);
INSERT INTO TEAM VALUES(18,'WEST BROM',1);
INSERT INTO TEAM VALUES(19,'WEST HAM',1);
INSERT INTO TEAM VALUES(20,'WIGAN',1);

INSERT INTO TEAM VALUES(21,'AC MILAN',2);
INSERT INTO TEAM VALUES(22,'INTER MILAN',2);
INSERT INTO TEAM VALUES(23,'JUVENTUS',2);
INSERT INTO TEAM VALUES(24,'AS ROMA',2);
INSERT INTO TEAM VALUES(25,'NAPOLI',2);
INSERT INTO TEAM VALUES(26,'UDINESE',2);

INSERT INTO TEAM VALUES(27,'REAL MADRID',3);
INSERT INTO TEAM VALUES(28,'BARCELONA',3);
INSERT INTO TEAM VALUES(29,'VALENCIA',3);
INSERT INTO TEAM VALUES(30,'ATLETICO MADRID',3);
INSERT INTO TEAM VALUES(31,'MALAGA',3);

INSERT INTO TEAM VALUES(32,'PARIS ST GERMAIN',4);
INSERT INTO TEAM VALUES(33,'LYON',4);
INSERT INTO TEAM VALUES(34,'MARSEILLE',4);
INSERT INTO TEAM VALUES(35,'LILLE',4);

INSERT INTO TEAM VALUES(36,'BAYERN MUNICH',5);
INSERT INTO TEAM VALUES(37,'DORTMUND',5);
INSERT INTO TEAM VALUES(38,'SCHALKE 04',5);
INSERT INTO TEAM VALUES(39,'HAMBURG',5);

INSERT INTO SOURCE VALUES (1,'The Guardian');
INSERT INTO SOURCE VALUES (2,'BBC News');
INSERT INTO SOURCE VALUES (3,'ESPN');